# Tested on Windows 11 with NVIDIA GPU (CUDA driver 13.0, PyTorch CUDA 12.1 build)
# Use: conda env create -f environment.yml

name: resume-matcher
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  # Core scientific stack
  - numpy
  - pandas
  - scikit-learn
  - scipy
  - joblib
  - tqdm
  - matplotlib
  - seaborn
  - wordcloud
  # NLP / ML essentials
  - faiss-cpu
  - nltk
  - statsmodels
  - huggingface_hub
  # File handling
  - openpyxl
  - lxml
  - pillow
  - pyyaml
  - python-docx
  - pdfminer.six
  # pip-only packages
  - pip:
      - sentence-transformers
      - transformers
      - accelerate
      - datasets
