name: resume-matcher
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  # --- Core Application Dependencies ---
  - fastapi
  - uvicorn
  - streamlit
  - altair
  - pandas
  - scikit-learn
  - joblib
  - pytorch
  - faiss-cpu
  - huggingface_hub
  - pdfminer.six
  - python-docx
  - requests
  - nltk
  - scipy
  - anyio
  # --- Pip-only packages ---
  - pip:
      - sentence-transformers
      - python-multipart